version: '3'

services:

  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    environment:
      ASR_MODEL: small
    ports:
      - "9000:9000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  thorsten:
    image: ghcr.io/coqui-ai/tts
    ports:
      - "50021:5002"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    entrypoint: "/bin/bash"
    command: "python3 TTS/server/server.py --model_name tts_models/de/thorsten/vits --use_cuda true"